title: AESBCSUM
description: Association des Étudiants en Sciences Biomédicales aux Cycles Supérieurs de l'Université de Montréal
url: "https://aesbcsum.github.io"

# Paramètres du site
lang: fr
email: aesbcsum@gmail.com

# Désactiver le thème par défaut pour utiliser notre layout personnalisé
theme: 

# Plugin Jekyll pour GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Configuration Markdown
markdown: kramdown
highlighter: rouge

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
